format_version: 10
pipelines:
  MutableDeployment_Backend:
    group: defaultGroup
    environment_variables:
      ENV: ""
      APP_VERSION: ""
    parameters:
      COMPONENT: backend
    materials:
      deploy:
        git: https://github.com/raghudevopsb76/expense-ansible
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
    - dev:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
            type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                command: bash
                arguments:
                  - mutable.sh
                run_if: passed

    - qa:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
            type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                command: echo
                arguments:
                  - "Deploying to QA Env"
                run_if: passed

    - uat:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
            type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                command: echo
                arguments:
                  - "Deploying to UAT Env"
                run_if: passed

    - prod:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
            type: manual
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                command: echo
                arguments:
                  - "Deploying to Prod Env"
                run_if: passed

